### ISSUE TITLE
Problem with Null Byte

### ISSUE THREAD

**Issue by tux4ever** [ElderByte-/ngx-stomp#3]
We had an issue within the parsing process, where a NULL Byte was always set at the last position. The problem ist in the file stomp-frame-parser.ts in the funciton deserializeFrame.

```typescript
if (clen) {
    let len = parseInt(clen);
    body = ('' + data).substring(start, start + len);
} else {
    let chr: string;
    for (let i = 0; i < data.length; i++) {
        chr = data.charAt(i);
        if (chr === BYTE.NULL) {
            break;
        }
        body += chr;
    }
}
```
If a conentent length is provided the body is taken from that provided length, but there is no check if it contains a NULL byte. This is only done in the else branch.

I think on option could be, regardless if a content length is provided to check for the null byte on every position, or at least at the end.

**Comment by IsNull** [comment]
Thank you for bringing this to our attention. I have a look - its quite possible that something is lacking in the binary support as we have currently no use case where we handle binary data with this protocol.

**Comment by tux4ever** [comment]
It might be a problem, but currently we use spring boot on the server side and do not send binary data. It is just a simple data object. The interesting point is, that the added NULL Byte at the end depends on the size of the content. If the text length of some fields within the dto is small it is working fine, but if the text increases we see the trailing NULL byte. Maybe it has something to do with multiple frames.

**Comment by IsNull** [comment]
I have looked into it:

>The SEND, MESSAGE and ERROR frames SHOULD include a content-length header if a frame body is present. If a frame's body contains NULL octets, the frame MUST include a content-length header. The header is a byte count for the length of the message body. If a content-length header is included, this number of bytes MUST be read, regardless of whether or not there are null characters in the body. The frame still needs to be terminated with a null byte.

Now I think (but don't know for sure) that the terminating null byte is not part of the provided content length. In the case of spring, it probably is. The question is what is correct.

Because simply ignoring the last null byte may cause issues in other cases.

**Comment by IsNull** [comment]
I had a look into the spring code and it appears that it handles the content length properly - at least as far as I could tell. [StompEncoder](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompEncoder.java)

```java
output.write(command.toString().getBytes(StandardCharsets.UTF_8));
output.write(LF);
writeHeaders(command, headers, payload, output);
output.write(LF);
writeBody(payload, output);
output.write((byte) 0);
```


```java
if (command.requiresContentLength()) {
	int contentLength = payload.length;
	output.write("content-length:".getBytes(StandardCharsets.UTF_8));
	output.write(Integer.toString(contentLength).getBytes(StandardCharsets.UTF_8));
	output.write(LF);
}
```

I guess I write a unit test for this case to ensure we handle it correctly on our side.

**Comment by FelsGorilla** [comment]
I am having a similar problem when an escaped JSON Object is sent as a message.
When ngx-stomp runs JSON.parse on the message, it runs into exception if the JSON-Data has special german characters like ß,äöü in it. 
My workaround is to replace the nullbyte in message.body and parsing it afterwards as json. 
Woks so far.

**Comment by mcs** [comment]
I think that the underlying problem is the conversion from a byte sequence to a character sequence, especially when using UTF-8. While some text characters are shipped within a single byte (usually all ASCII characters), more "exotic" characters (like german umlauts) need two or even more bytes within a byte array. Because of this, the converted string representation may contain less characters than the byte array:
```    
        byte[] helloWorld = "Hello World".getBytes(StandardCharsets.UTF_8);
        byte[] helloUmlaut = "Hello Wörld".getBytes(StandardCharsets.UTF_8);

        System.out.println(helloWorld.length);  // 11
        System.out.println(helloUmlaut.length); // 14 !!

        String helloWorldStr = new String(helloWorld, StandardCharsets.UTF_8);
        String helloUmlautStr = new String(helloWorld, StandardCharsets.UTF_8);

        System.out.println(helloWorldStr.length());  // 11
        System.out.println(helloUmlautStr.length()); // 11
```

**Comment by IsNull** [comment]
@mcs Thanks for your explanation, I think I see the problem now:

`body = ('' + data).substring(start, start + len);`

This turns the data into a string and the use the raw byte array length to shorten it - which as you explained may differ due to Unicode encoding, which can use up to 4 bytes per character.
I think I should be able to finally fix this!

**Comment by IsNull** [comment]
I have separated the STOMP core logic from the Angular stuff to [@elderbyte/ts-stomp](https://github.com/ElderByte-/ts-stomp), this library now simply depends on the above.

With that out of the way, I have reworked the unmarshalling of the STOMP frames when the data arrives in a byte array. [It](https://github.com/ElderByte-/ts-stomp/blob/master/src/stomp/parser/stomp-frame-deserializer.ts) will now decode the byte array into a string using a [UTF8 decoder](https://github.com/ElderByte-/ts-stomp/blob/master/src/stomp/parser/text-encoding.ts).

This means that now the message body should work properly when it is encoded in UTF8, so there should no longer be issues with special chars. As a bonus, the ending Null-Byte should be gone as well.

Let me know if `5.3.0-beta` works for you.

**Comment by FelsGorilla** [comment]
Thanks. I tested 5.3.0-beta and it's working as expected.

**Comment by IsNull** [comment]
Thanks for the feedback
